apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /home/wso2carbon/wso2am-4.0.0/repository/logs/apim_metrics.log
      include_lines: ['(apimMetrics):']
    output.logstash:
      hosts: ["192.168.92.113:5044"]
